### PR TITLE
Fixes outstanding requirements for front end user authorization messages

### PR DESCRIPTION
**Pull request by Azinck94**
-Adds a success message in the modal for users who change their password
-Removed password confirmation field, avoiding necessity for pw and pw confirmation matching altogether.
-Adds credits for sleeping samurai to the landing page

### CODE REVIEW

**Comment by CoreyFedde** [comment]
Looks good to me!

**Comment by kailinc** [comment]
just

**Comment by kailinc** [comment]
wow

**Comment by kailinc** [comment]
!

**Pull request merged**
